services:
  db:
    image: postgres:16
    container_name: carrental_db
    environment:
      POSTGRES_DB: carrental
      POSTGRES_USER: caruser
      POSTGRES_PASSWORD: carpass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: carrental_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
volumes:
  pgdata:
