"""create core tables from models.py

Revision ID: 85046ed6f53a
Revises: e6e95da84641
Create Date: 2025-09-15 20:17:27.768541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85046ed6f53a'
down_revision = 'e6e95da84641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('brand_primary', sa.String(length=9), nullable=True),
    sa.Column('brand_navbar_bg', sa.String(length=9), nullable=True),
    sa.Column('brand_sidebar_bg', sa.String(length=9), nullable=True),
    sa.Column('terms_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('mail_from_name', sa.String(length=120), nullable=True),
    sa.Column('mail_from_email', sa.String(length=120), nullable=True),
    sa.Column('mail_secret_id', sa.String(length=200), nullable=True),
    sa.Column('mail_provider', sa.String(length=30), nullable=True),
    sa.Column('payment_secret_id', sa.String(length=200), nullable=True),
    sa.Column('payment_endpoint', sa.String(length=255), nullable=True),
    sa.Column('gp_pub_key', sa.String(length=255), nullable=True),
    sa.Column('gp_token', sa.String(length=255), nullable=True),
    sa.Column('gp_merchant_code', sa.String(length=64), nullable=True),
    sa.Column('gp_payment_endpoint', sa.String(length=255), nullable=True),
    sa.Column('contract_template_html', sa.Text(), nullable=True),
    sa.Column('sign_x_rel', sa.Float(), nullable=True),
    sa.Column('sign_y_rel', sa.Float(), nullable=True),
    sa.Column('sign_w_pt', sa.Integer(), nullable=True),
    sa.Column('sign_h_pt', sa.Integer(), nullable=True),
    sa.Column('rub_w_pt', sa.Integer(), nullable=True),
    sa.Column('rub_h_pt', sa.Integer(), nullable=True),
    sa.Column('rub_margin_pt', sa.Integer(), nullable=True),
    sa.Column('rubrica_on_last', sa.Boolean(), nullable=True),
    sa.Column('audit_stamp', sa.Boolean(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('weekly_min', sa.Integer(), nullable=False),
    sa.Column('unlock_price_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('to_be_deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('pickup_airport', sa.String(length=80), nullable=True),
    sa.Column('dropoff_airport', sa.String(length=80), nullable=True),
    sa.Column('pickup_dt', sa.DateTime(), nullable=True),
    sa.Column('dropoff_dt', sa.DateTime(), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_leads_tenant_id'), 'leads', ['tenant_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('amount_gross_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fee_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('amount_fee_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_paid_at'), 'payments', ['paid_at'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.create_table('usage_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('rentals_last_7d', sa.Integer(), nullable=False),
    sa.Column('reached_min', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_snapshots_taken_at'), 'usage_snapshots', ['taken_at'], unique=False)
    op.create_index(op.f('ix_usage_snapshots_tenant_id'), 'usage_snapshots', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('email_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('vehicle_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('transmission', sa.String(length=20), nullable=True),
    sa.Column('large_bags', sa.Integer(), nullable=True),
    sa.Column('small_bags', sa.Integer(), nullable=True),
    sa.Column('mileage_text', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_categories_slug'), 'vehicle_categories', ['slug'], unique=False)
    op.create_index(op.f('ix_vehicle_categories_tenant_id'), 'vehicle_categories', ['tenant_id'], unique=False)
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('daily_rate', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('deposit_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['vehicle_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rates_category_id'), 'rates', ['category_id'], unique=False)
    op.create_index(op.f('ix_rates_tenant_id'), 'rates', ['tenant_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(length=32), nullable=True),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['vehicle_categories.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate')
    )
    op.create_index(op.f('ix_vehicles_category_id'), 'vehicles', ['category_id'], unique=False)
    op.create_index(op.f('ix_vehicles_tenant_id'), 'vehicles', ['tenant_id'], unique=False)
    op.create_table('maintenance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_logs_tenant_id'), 'maintenance_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_maintenance_logs_vehicle_id'), 'maintenance_logs', ['vehicle_id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('customer_doc', sa.String(length=120), nullable=True),
    sa.Column('customer_country', sa.String(length=80), nullable=True),
    sa.Column('customer_city_uf', sa.String(length=120), nullable=True),
    sa.Column('flight_no', sa.String(length=40), nullable=True),
    sa.Column('pickup_airport', sa.String(length=64), nullable=False),
    sa.Column('pickup_dt', sa.DateTime(), nullable=False),
    sa.Column('dropoff_airport', sa.String(length=64), nullable=False),
    sa.Column('dropoff_dt', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('gp_order_id', sa.String(length=64), nullable=True),
    sa.Column('gp_installments', sa.Integer(), nullable=True),
    sa.Column('gp_payment_status', sa.String(length=32), nullable=True),
    sa.Column('gp_payment_method', sa.String(length=64), nullable=True),
    sa.Column('gp_auth_code', sa.String(length=64), nullable=True),
    sa.Column('gp_amount_brl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gp_amount_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gp_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['vehicle_categories.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_category_id'), 'reservations', ['category_id'], unique=False)
    op.create_index(op.f('ix_reservations_created_at'), 'reservations', ['created_at'], unique=False)
    op.create_index(op.f('ix_reservations_gp_order_id'), 'reservations', ['gp_order_id'], unique=False)
    op.create_index(op.f('ix_reservations_status'), 'reservations', ['status'], unique=False)
    op.create_index(op.f('ix_reservations_tenant_id'), 'reservations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_reservations_vehicle_id'), 'reservations', ['vehicle_id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('signature_type', sa.String(), nullable=True),
    sa.Column('signature_hash', sa.String(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_index(op.f('ix_contracts_reservation_id'), 'contracts', ['reservation_id'], unique=True)
    op.create_table('operator_checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('marks', sa.JSON(), nullable=False),
    sa.Column('fuel_level', sa.Integer(), nullable=True),
    sa.Column('odometer', sa.Integer(), nullable=True),
    sa.Column('notes_ext', sa.Text(), nullable=True),
    sa.Column('notes_int', sa.Text(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('signature_path', sa.String(length=255), nullable=True),
    sa.Column('operator_name', sa.String(length=120), nullable=True),
    sa.Column('customer_name', sa.String(length=120), nullable=True),
    sa.Column('customer_email', sa.String(length=120), nullable=True),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_checklists_reservation_id'), 'operator_checklists', ['reservation_id'], unique=False)
    op.alter_column('prospects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('prospects', 'last_contact_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_prospects_created_at'), 'prospects', ['created_at'], unique=False)
    op.create_index(op.f('ix_prospects_email'), 'prospects', ['email'], unique=False)
    op.create_index(op.f('ix_prospects_status'), 'prospects', ['status'], unique=False)
    op.add_column('support_messages', sa.Column('sender', sa.String(length=20), nullable=False))
    op.add_column('support_messages', sa.Column('body', sa.Text(), nullable=False))
    op.alter_column('support_messages', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('support_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_support_messages_created_at'), 'support_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_support_messages_tenant_id'), 'support_messages', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'support_messages', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('support_messages', 'name')
    op.drop_column('support_messages', 'message')
    op.drop_column('support_messages', 'subject')
    op.drop_column('support_messages', 'updated_at')
    op.drop_column('support_messages', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_messages', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('support_messages', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('support_messages', sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('support_messages', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('support_messages', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'support_messages', type_='foreignkey')
    op.drop_index(op.f('ix_support_messages_tenant_id'), table_name='support_messages')
    op.drop_index(op.f('ix_support_messages_created_at'), table_name='support_messages')
    op.alter_column('support_messages', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('support_messages', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('support_messages', 'body')
    op.drop_column('support_messages', 'sender')
    op.drop_index(op.f('ix_prospects_status'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_email'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_created_at'), table_name='prospects')
    op.alter_column('prospects', 'last_contact_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('prospects', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_operator_checklists_reservation_id'), table_name='operator_checklists')
    op.drop_table('operator_checklists')
    op.drop_index(op.f('ix_contracts_reservation_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_reservations_vehicle_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_tenant_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_status'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_gp_order_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_created_at'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_category_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_maintenance_logs_vehicle_id'), table_name='maintenance_logs')
    op.drop_index(op.f('ix_maintenance_logs_tenant_id'), table_name='maintenance_logs')
    op.drop_table('maintenance_logs')
    op.drop_index(op.f('ix_vehicles_tenant_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_category_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_rates_tenant_id'), table_name='rates')
    op.drop_index(op.f('ix_rates_category_id'), table_name='rates')
    op.drop_table('rates')
    op.drop_index(op.f('ix_vehicle_categories_tenant_id'), table_name='vehicle_categories')
    op.drop_index(op.f('ix_vehicle_categories_slug'), table_name='vehicle_categories')
    op.drop_table('vehicle_categories')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_usage_snapshots_tenant_id'), table_name='usage_snapshots')
    op.drop_index(op.f('ix_usage_snapshots_taken_at'), table_name='usage_snapshots')
    op.drop_table('usage_snapshots')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_paid_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_leads_tenant_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_created_at'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
