"""Site builder models

Revision ID: 9c7fde03ffe9
Revises: 2dee0e47b921
Create Date: 2025-09-19 17:12:47.504199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c7fde03ffe9'
down_revision = '2dee0e47b921'
branch_labels = None
depends_on = None


def _table_exists(table_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    try:
        return table_name in inspector.get_table_names()
    except Exception:
        return False


def _index_exists(table_name: str, index_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    try:
        indexes = inspector.get_indexes(table_name)
    except Exception:
        return False
    return any(idx["name"] == index_name for idx in indexes)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists("media_assets"):
        op.create_table(
            "media_assets",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("tenant_id", sa.Integer(), nullable=False),
            sa.Column("filename", sa.String(length=255), nullable=False),
            sa.Column("content_type", sa.String(length=80), nullable=True),
            sa.Column("url", sa.String(length=255), nullable=False),
            sa.Column("size_bytes", sa.Integer(), nullable=True),
            sa.Column("alt_text", sa.String(length=200), nullable=True),
            sa.Column("tags", sa.String(length=200), nullable=True),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
    if not _table_exists("sites"):
        op.create_table(
            "sites",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("tenant_id", sa.Integer(), nullable=False),
            sa.Column("is_enabled", sa.Boolean(), nullable=False),
            sa.Column("is_published", sa.Boolean(), nullable=False),
            sa.Column("published_at", sa.DateTime(), nullable=True),
            sa.Column("theme", sa.String(length=50), nullable=False),
            sa.Column("primary_color", sa.String(length=9), nullable=True),
            sa.Column("secondary_color", sa.String(length=9), nullable=True),
            sa.Column("font_family", sa.String(length=120), nullable=True),
            sa.Column("logo_url", sa.String(length=255), nullable=True),
            sa.Column("hero_image_url", sa.String(length=255), nullable=True),
            sa.Column("site_title", sa.String(length=120), nullable=True),
            sa.Column("site_description", sa.String(length=300), nullable=True),
            sa.Column("site_keywords", sa.String(length=300), nullable=True),
            sa.Column("ai_copy_enabled", sa.Boolean(), nullable=False),
            sa.Column("ai_image_enabled", sa.Boolean(), nullable=False),
            sa.Column("custom_domain", sa.String(length=255), nullable=True),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"]),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("tenant_id"),
        )
    if not _table_exists("site_pages"):
        op.create_table(
            "site_pages",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("site_id", sa.Integer(), nullable=False),
            sa.Column("title", sa.String(length=120), nullable=False),
            sa.Column("slug", sa.String(length=120), nullable=False),
            sa.Column("order", sa.Integer(), nullable=False),
            sa.Column("is_home", sa.Boolean(), nullable=False),
            sa.Column("meta_title", sa.String(length=120), nullable=True),
            sa.Column("meta_description", sa.String(length=300), nullable=True),
            sa.Column("meta_keywords", sa.String(length=300), nullable=True),
            sa.Column("og_image_url", sa.String(length=255), nullable=True),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(["site_id"], ["sites.id"]),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("site_id", "slug", name="uq_site_page_slug"),
        )
    if not _table_exists("site_blocks"):
        op.create_table(
            "site_blocks",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("page_id", sa.Integer(), nullable=False),
            sa.Column("block_type", sa.String(length=40), nullable=False),
            sa.Column("payload", sa.JSON(), nullable=False),
            sa.Column("order", sa.Integer(), nullable=False),
            sa.Column("is_visible", sa.Boolean(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(["page_id"], ["site_pages.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
    if _table_exists("vehicle_maintenance"):
        idx_active = op.f("ix_vehicle_maintenance_active")
        idx_tenant = op.f("ix_vehicle_maintenance_tenant_id")
        idx_vehicle = op.f("ix_vehicle_maintenance_vehicle_id")
        if _index_exists("vehicle_maintenance", idx_active):
            op.drop_index(idx_active, table_name="vehicle_maintenance")
        if _index_exists("vehicle_maintenance", idx_tenant):
            op.drop_index(idx_tenant, table_name="vehicle_maintenance")
        if _index_exists("vehicle_maintenance", idx_vehicle):
            op.drop_index(idx_vehicle, table_name="vehicle_maintenance")
        op.drop_table("vehicle_maintenance")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists("vehicle_maintenance"):
        op.create_table(
            "vehicle_maintenance",
            sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
            sa.Column("tenant_id", sa.INTEGER(), autoincrement=False, nullable=False),
            sa.Column("vehicle_id", sa.INTEGER(), autoincrement=False, nullable=False),
            sa.Column("reason", sa.TEXT(), autoincrement=False, nullable=True),
            sa.Column("started_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
            sa.Column("ended_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
            sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=True),
            sa.PrimaryKeyConstraint("id", name=op.f("vehicle_maintenance_pkey")),
        )
    if _table_exists("vehicle_maintenance"):
        idx_vehicle = op.f("ix_vehicle_maintenance_vehicle_id")
        idx_tenant = op.f("ix_vehicle_maintenance_tenant_id")
        idx_active = op.f("ix_vehicle_maintenance_active")
        if not _index_exists("vehicle_maintenance", idx_vehicle):
            op.create_index(idx_vehicle, "vehicle_maintenance", ["vehicle_id"], unique=False)
        if not _index_exists("vehicle_maintenance", idx_tenant):
            op.create_index(idx_tenant, "vehicle_maintenance", ["tenant_id"], unique=False)
        if not _index_exists("vehicle_maintenance", idx_active):
            op.create_index(idx_active, "vehicle_maintenance", ["active"], unique=False)
    if _table_exists("site_blocks"):
        op.drop_table("site_blocks")
    if _table_exists("site_pages"):
        op.drop_table("site_pages")
    if _table_exists("sites"):
        op.drop_table("sites")
    if _table_exists("media_assets"):
        op.drop_table("media_assets")
    # ### end Alembic commands ###
