name: Build & Deploy 4uFleet (Container)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_CLIENT_ID:        ${{ vars.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID:        ${{ vars.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID:  ${{ vars.AZURE_SUBSCRIPTION_ID }}
  ACR_NAME:               ${{ vars.ACR_NAME }}
  ACR_LOGIN_SERVER:       ${{ vars.ACR_LOGIN_SERVER }}
  IMAGE_NAME:             ${{ vars.IMAGE_NAME }}
  RESOURCE_GROUP:         ${{ vars.RESOURCE_GROUP }}
  WEBAPP_NAME:            ${{ vars.WEBAPP_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to ACR
        run: az acr login -n $ACR_NAME

      - name: Build & push image to ACR
        run: |
          IMAGE="$ACR_LOGIN_SERVER/$IMAGE_NAME"
          docker build -t "$IMAGE:${{ github.sha }}" -t "$IMAGE:latest" .
          docker push "$IMAGE:${{ github.sha }}"
          docker push "$IMAGE:latest"

      - name: Restart App Service
        run: az webapp restart -g "$RESOURCE_GROUP" -n "$WEBAPP_NAME"
